<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Home extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
		$this->load->view('home');
        
    } 

    public function loginadmin(){  
    $this->load->view('dashboard_admin');
    }

    public function loginmember(){
    $this->load->view('dashboard_member');
    }

    public function member(){
        $this->load->view('loginmember');
    }

    public function signup(){
        $this->load->view('signup');
    }
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */