<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login_member extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Member_model');
    }

    public function index()
    {
		if($this->session->userdata('logined_member') && $this->session->userdata('logined_member') == true)
		{
			redirect('Home/loginmember');
		}
		if(!$this->input->post())
		{
			$this->load->view('loginmember');
		}
		else
		{
			$cek_login=$this->Member_model->cek_login(
				$this->input->post('email'),
				$this->input->post('password')		
			);
			if(!empty($cek_login))
			{
				$this->session->set_userdata('logined_member', true);
				$this->session->set_userdata('email', $cek_login->email);
				redirect('Post/postmember');
			}
			else 
			{
				redirect("/");
			}
		}  
    } 
	
	public function logoutmember()
    {
		$this->session->unset_userdata('logined_member');
		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */